### ISSUE TITLE
✨ feat: dummy data image all upload

### ISSUE THREAD

**Issue by hpsmart2017** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#11]
# Title

- dummy data image all upload

# TODO

- [ ] 올려놓은 .zip 파일 확인 해주시고 사용할 이미지들 문제 없는지 체크해주세요. 

# etc
[7,8월 플젝 dummy data image.zip](https://github.com/user-attachments/files/16505184/7.8.dummy.data.image.zip)
- 확인 완료되면 .zip파일 삭제 후 이미지 폴더로 만들어 놓을 예정입니다.

**Comment by Daehyun-Bigbread** [comment]
일단 수업 끝나고 확인해볼께요! 아 그리고 주노주노 그 혹시 JIRA에 티켓 생성하셨나요? 안생성 하셨으면 코위코가 만들어둔 가이드 있어요 노션페이지에, 그거 보고 그렇게 작성해주세요!!

**Comment by Daehyun-Bigbread** [comment]
준호님 좋은거 같아요! 사진 다 확인했고, repo에 한번 올려주세요! 그리고 FE에서도 확인해 볼수 있게 슈슈에게도 한번 얘기 해주세요!
