### ISSUE TITLE
✨ feat: dummy_data_upload_check

### ISSUE THREAD

**Issue by hpsmart2017** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#12]
# Title

-  더미데이터용 이미지 확인

# TODO

[dummy_data_image](https://github.com/Kakaotech-18-Ecommerce/Kakaotech-18-AI/tree/db32b05e43f8cb85b5ecbad5ad763bf8405abf09/dummy_data_image)

- 더미데이터용 이미지 확인 부탁드립니다. 
# etc

- 어쩌구저쩌구

**Comment by Daehyun-Bigbread** [comment]
이미지 확인했으니까 issue 닫겠습니다! 지라 티켓으로 해야할 Task랑 이슈 만들어 놓을께요!
