### ISSUE TITLE
✨ feat: Data Image & Product ID Matching

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#24]
# Title

- 데이터 사진과 Product_id 사진 매칭 작업

# TODO

- [x] 더미데이터 사진명을 product.json의 product_id와 matching 시키기

# etc

- @hpsmart2017 주노님! 늦은시간에 이슈 올려서 죄송해요! 준호님이 수집해주신 사진 데이터와 저희 product.json 파일 안에 product_id 숫자 값이랑 동일하게 매칭시켜 주셔야 하거든요? 작업 부탁드릴께요!

**Comment by hpsmart2017** [comment]
toby, 
product.json 파일 안에 product_image 요소를 이미지 파일 이름이랑 맞추고, 경로 설정을 위해서 dummy data 폴더 안에 새로 이미지 폴더 만들어 옮기면 될 것 같은데, 이것만 하면 matching이 될지 확신이 안 들어서 메세지 남겨요.
그대로 진행해도 되는 거면 확인 표시 남겨주세요!

**Comment by Daehyun-Bigbread** [comment]
@hpsmart2017 이 작업은 저희가 product_id에 해당하는 이미지랑 매칭시키고, 이걸 FE에 띄울거에요! 그래서 나중에 디렉토리 형태는 슈슈랑 한번 얘기를 해봐야 하는데, 일단 FE개발 초안이 나와야 변경할수 있는거니까, 일단은 그대로 진행해주셔도 될거 같아요! 저도 빨리 Test Model 개발해서 PR 할께요!
