### ISSUE TITLE
✨ feat: dummydata 생성

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#4]
# Title

- dummydata 만들기

# TODO

- [x] buyers.json
- [x] carts.json
- [x] order_products.json
- [x] orders.json
- [x] products.json
- [x] reviews.json
- [x] sellers.json

# etc

- 추천시스템용 가상 데이터 입니다! 만약 괜찮으면 프로젝트에 실제로 넣을수도 있어여

**Comment by hpsmart2017** [comment]
**GOOD!**
다른 팀원분들도 체크하면 좋을 것 같아요!
