### ISSUE TITLE
✨ feat: Create dummy data

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#6]
# Title

- Create dummy data

# TODO

- [x] Kakao_Dummydata.ipynb

# etc

- 서비스에 넣을 더미 데이터 생성 작업입니다.

**Comment by Daehyun-Bigbread** [comment]
JIRA 잘못 써서 다시 정리하고 올릴께요! 죄송합니다.. 좀 어렵네요 ㅠㅠㅠ @hpsmart2017

**Comment by hpsmart2017** [comment]
괜찮아요!
